import 'dart:math';

class GreetingHelper {
  GreetingHelper._();

  static final Random _random = Random();

  static const List<String> greetings = [
    "Hey, radar contact! What’s on your mind today?",
    "Hello captain — ready for pushback into a new topic?",
    "Roger that, you’re online. What’s our first waypoint?",
    "Welcome back! Cockpit’s yours — where do we fly first?",
    "Cleared for takeoff into knowledge. What’s your question?",
    "Hey there! Taxi instructions filed — where should we roll?",
    "Good to see you. Shall we climb into something tricky today?",
    "Roger, flight plan received. What’s the first fix?",
    "Welcome aboard! Which altitude of curiosity are we aiming for?",
    "Hello! You’re cleared onto the active — what’s the next question?",
    "Roger, you’re squawking curiosity. What’s the frequency?",
    "Cabin crew ready, passengers seated — what’s the destination?",
    "Hey pilot buddy — shall we shoot an approach into today’s topic?",
    "Roger that. Do we cruise high or keep it low and simple?",
    "Welcome back, aviator! What’s the first leg of today’s journey?",
    "Engines running, checklist complete — where do we head?",
    "Hello again! Shall we chase some turbulence in the regs today?",
    "Roger. ATIS received. What’s your clearance request?",
    "Fasten seatbelts! What’s our heading in this session?",
    "Welcome! Cross-check complete — shall we roll?",
    "Hey there! I’m tuned in and ready. What’s your traffic?",
    "Roger, cleared direct curiosity VOR. What’s your radial?",
    "Hello pilot! Ready to rotate into something new?",
    "We’re lined up. Question is: throttle up or hold short?",
    "Good day! Let’s file a flight plan through your questions.",
    "Roger. Your call sign’s loud and clear. Where to first?",
    "Hey buddy! Shall we intercept the knowledge localizer?",
    "Welcome back! Do we track a simple route or detour into detail?",
    "Cabin doors armed, slides cross-checked. What shall we learn today?",
    "Roger. Ready for departure when you are — destination?",
    "Hello! Flight controls free and correct — what’s next?",
    "Hey! We’re holding short of curiosity runway. Do we line up?",
    "Roger, you’re identified on scope. What’s our separation today?",
    "Welcome aboard! Do we fly VFR questions or IFR detail?",
    "Cockpit coffee brewed. What’s today’s briefing?",
    "Roger. Wind calm, runway in use — question?",
    "Hello aviator! We can climb, descend, or cruise — your choice.",
    "Hey there! Beacon’s on — shall we taxi?",
    "Roger that. Flight directors set — what’s your command?",
    "Welcome! Pre-flight done. Ready for curiosity pushback?",
    "Good to see you! Shall we file an alternate route of ideas?",
    "Roger. Fuel loaded, charts ready. Where do we start?",
    "Hey pilot! Ready to shoot the breeze and the approach?",
    "Hello! Control checks complete. Question clearance?",
    "Roger. You’ve got priority handling. What’s your request?",
    "Welcome back! Shall we chase some contrails of thought?",
    "Hey, squawk 7700 — just kidding. What’s your question?",
    "Roger. Cabin secure, flaps set. Do we roll?",
    "Hello! Runway’s clear — question for takeoff?",
    "Welcome, aviator. Altimeter set. What’s your next vector?",
    "Hey buddy! Do we climb into performance data or descend into history?",
    "Roger. ATC slot confirmed. What’s your clearance?",
    "Good day! Flight deck lights are green. Where do we taxi?",
    "Hello again! Do we hold short of trivia or line up for deep dive?",
    "Roger. Maintenance signed off. You’re cleared. What’s up?",
    "Welcome! TCAS clear. Which direction shall we explore?",
    "Hey! Call sign identified. Do we track the airway or cut direct?",
    "Roger. You’ve got runway priority. Question when ready.",
    "Welcome captain. Today we can climb high or circle low. Which one?",
    "Hello there! Seatbelts on, curiosity armed. What’s the flight plan?",
    "Roger, I have you on frequency. What’s our flight plan today?",
    "Hey, cleared direct to curiosity. What’s your next waypoint?",
    "Welcome back! Ready to rotate into your next challenge?",
    "Roger that. Do we climb through data or cruise in trivia?",
    "Hello! Ground is clear — shall we taxi to runway ideas?",
    "Hey captain, checklist complete. What’s the departure clearance?",
    "Roger. You’ve got a clear frequency. What’s your request?",
    "Welcome aboard! Doors to automatic — where do we fly?",
    "Hello aviator! Shall we descend into details or hold at overview?",
    "Roger, you’re squawking curiosity 7700… just joking. What’s your topic?",
    "Hey there! You’re established on the localizer. Shall we continue?",
    "Roger. Flight plan loaded. Where shall we navigate first?",
    "Welcome back. TCAS shows clear skies — question ready?",
    "Hello pilot! Time to push the throttle on knowledge?",
    "Roger. Cabin secure, engines spooling. What’s your destination?",
    "Hey buddy! Charts are open. What’s our route today?",
    "Roger that. Flaps set, spoilers armed — let’s go!",
    "Welcome! Do we shoot an ILS of detail or a visual of basics?",
    "Hello! ATC just gave us direct clearance. What’s yours?",
    "Roger. Radios checked, squawk set. What’s your request?",
    "Hey, welcome back! Ready to cross-check some facts?",
    "Roger. Heading bug set on curiosity. What’s our course?",
    "Hello aviator! You’re cleared onto the active. Question?",
    "Hey there! What sector of airspace shall we explore today?",
    "Roger. We’re rolling — do we level at basics or climb to advanced?",
    "Welcome back! Ready to intercept the knowledge radial?",
    "Hello! Ground speed high, tailwind strong — shall we dive in?",
    "Roger. Brake check complete — let’s taxi into your question.",
    "Hey, what squawk code of curiosity do we dial today?",
    "Roger that. Weather looks good. Destination?",
    "Hello buddy! Flight attendants ready — what’s our mission?",
    "Welcome back! Do we climb into theory or cruise in practice?",
    "Roger. You’re airborne on curiosity runway. What’s next fix?",
    "Hey captain! Shall we intercept some crosswinds of thought?",
    "Roger that. Question traffic ahead, maintain separation. Go ahead!",
    "Hello! Cabin secure, cross-check complete. What’s our next heading?",
    "Welcome! We can hold pattern or proceed direct — your call.",
    "Roger. Nav lights on, flight path open. What’s your clearance?",
    "Hey there! You’re top of climb. Do we continue cruise or plan descent?",
    "Roger that. Curiosity fuel tanks full — where do we burn first?",

    // Meteorology
    "Hello! Skies clear, CAVOK today. What’s your question?",
    "Roger. Storm cells on the horizon — shall we navigate through some tricky topics?",
    "Hey there! High pressure here — stable conditions for learning. Where do we start?",
    "Welcome back! Visibility unlimited — ready to explore?",
    "Roger. Ceiling’s unlimited. What altitude of knowledge shall we climb to?",
    "Hello! Winds calm, runway dry — your turn.",
    "Hey buddy! A low front of curiosity is moving in. What’s your clearance?",
    "Roger. Crosswinds strong — want to test your handling skills?",
    "Welcome! Icing conditions detected — shall we shed some misconceptions?",
    "Hello aviator! Light turbulence today — ready for a bumpy ride of questions?",
    "Roger. Temperature-dewpoint spread’s tight — fog of doubt forming? Let’s clear it.",
    "Hey there! Tailwind strong — we’ll cover ground fast. Where to?",
    "Hello! Thunderstorms on the chart — want to divert into safer questions or fly through?",
    "Roger. A jet stream of curiosity overhead. Do we ride it?",
    "Welcome back! Pressure rising — shall we climb?",
    "Hey captain! Winds aloft look favorable. Which heading?",
    "Roger. Heavy rain outside — but cockpit’s dry. What’s your request?",
    "Hello! Cloud layers stacked — do we start low or break through to the top?",
    "Welcome! Moderate chop expected — shall we test some tricky scenarios?",
    "Roger. QNH set, skies variable — what’s your fix?",
    "Hey! Broken cumulus ahead — shall we weave through some scattered questions?",
    "Hello! Temperature inversion detected — want to flip perspectives today?",
    "Roger. Dewpoint depression minimal — visibility dropping. Let’s keep things clear.",
    "Welcome back! Tailwind on climb — fast track to your answer?",
    "Hey buddy! Frontal system incoming — shall we cross it together?",

    // ATC
    "Hello! Tower here — you’re cleared to line up with your next question.",
    "Roger. You’re on my frequency now. State your request.",
    "Hey there! Radar contact established. What’s our heading?",
    "Welcome back! Flight strip printed — what’s your call sign today?",
    "Hello! Clearance delivery ready. Destination of curiosity?",
    "Roger. You’re number one for takeoff in the knowledge queue.",
    "Hey pilot buddy — ground frequency is all yours. Where to?",
    "Welcome aboard! ATIS received — conditions good. What’s next?",
    "Hello aviator! You’re identified. Maintain question flow and report ready.",
    "Roger. Departure frequency active. What’s your squawk of curiosity?",
    "Hey there! Tower lights are green. Shall we clear you for takeoff?",
    "Welcome back! Radar shows light traffic. Your question has priority.",
    "Hello! ATC coordination complete. You’re cleared direct to your topic.",
    "Roger. You’ve got the frequency. Report when ready.",
    "Hey captain! Controller coffee strong today — give me your best shot",
  ];

  static String getRandomGreeting() {
    return greetings[_random.nextInt(greetings.length)];
  }
}